POST http://127.0.0.1:8000/predict
Content-Type: application/json

{
  "cEE": 0.1,
  "cH2": 0.12,
  "cNG": 0.037,
  "cbioCH4": 0.07,
  "cbiomass": 0.01692,
  "cCoal": 0.011,
  "cMSW": 0.003,
  "cCO2": 0.080,
  "cCO2TnS": 0.060
}
